#!/usr/bin/env python3
"""
compass_reproduce.py — Independent Reproducibility Script for the Patient Compass Paper
========================================================================================

This script reproduces all statistical claims in the Patient Compass paper
using ONLY standard biostatistical methods:
  - Hallmark state census (8-bit binary vectors)
  - Pair completeness distribution + Boltzmann fit
  - Domain wall features (broken hallmark pairs)
  - Cox proportional hazards (via lifelines CoxPHFitter, Efron ties)
  - Tissue O₂ tier classification
  - Stouffer meta-analysis
  - Mann-Whitney survival stratification

NO eigenvalue computation, NO spectral methods, NO commutator algebra.
All methods here are textbook biostatistics / epidemiology.

Reads pre-downloaded data from compass_100k_results.json (generated by the
pipeline), or can fetch fresh from cBioPortal if --fetch is passed.

Usage:
    python compass_reproduce.py                    # Use cached data
    python compass_reproduce.py --fetch            # Fresh from cBioPortal
    python compass_reproduce.py --compact data.json # Use compact patient file

References:
    Matos, A. P. "The Patient Compass: A Thermodynamic Framework for
    Pan-Cancer Hallmark Survival Analysis." (2026).
"""

import numpy as np
import sys
import os
import time
import json
from collections import Counter
from math import erfc, log, exp, sqrt

os.environ['PYTHONUTF8'] = '1'
if hasattr(sys.stdout, 'reconfigure'):
    try:
        sys.stdout.reconfigure(encoding='utf-8')
    except Exception:
        pass

BAR = '=' * 80
n_h = 8

HALLMARKS = [
    'Proliferative_Signaling',      # 0
    'Growth_Suppression_Evasion',    # 1
    'Resisting_Cell_Death',          # 2
    'Replicative_Immortality',       # 3
    'Invasion_Metastasis',           # 4
    'Immune_Evasion',                # 5
    'Genome_Instability',            # 6
    'Deregulated_Metabolism',        # 7
]

SHORT = ['Prolif', 'GrowSup', 'Death', 'Immort', 'Invade', 'Immune', 'Genome', 'Metab']

# Biological hallmark pairs (Hanahan & Weinberg functional coupling)
PAIRS = [(0, 4), (1, 3), (2, 5), (6, 7)]

GENE_TO_HALLMARK = {
    'KRAS': [0], 'BRAF': [0], 'NRAS': [0], 'ERBB2': [0], 'ERBB3': [0],
    'MAP2K1': [0], 'FGFR2': [0], 'NF1': [0], 'PIK3CA': [0, 2],
    'TP53': [1, 2], 'APC': [1], 'RB1': [1], 'CDKN2A': [1],
    'SMAD4': [1], 'SMAD2': [1], 'SMAD3': [1], 'TGFBR2': [1],
    'FBXW7': [1], 'ACVR2A': [1], 'NOTCH1': [1], 'SOX9': [1],
    'TCF7L2': [1], 'RNF43': [1], 'AMER1': [1], 'CTNNB1': [1, 4],
    'PTEN': [2], 'CREBBP': [2], 'TSC2': [2],
    'ATRX': [3, 6],
    'CDH1': [4], 'FAT1': [4], 'FAT4': [4],
    'JAK1': [5],
    'MLH1': [6], 'MSH2': [6], 'MSH6': [6], 'PMS2': [6],
    'POLE': [6], 'BRCA2': [6], 'ATM': [6],
    'ARID1A': [6], 'KMT2C': [6], 'KMT2D': [6],
    'IDH1': [7], 'GNAS': [7],
}

GENES = [
    ('APC', 324),      ('TP53', 7157),    ('KRAS', 3845),    ('PIK3CA', 5290),
    ('SMAD4', 4089),   ('FBXW7', 55294),  ('BRAF', 673),     ('NRAS', 4893),
    ('PTEN', 5728),    ('CTNNB1', 1499),  ('RB1', 5925),     ('ATM', 472),
    ('RNF43', 54894),  ('SOX9', 6662),    ('TGFBR2', 7048),  ('TCF7L2', 6934),
    ('SMAD2', 4087),   ('AMER1', 139285), ('ACVR2A', 92),    ('ARID1A', 8289),
    ('BRCA2', 675),    ('ERBB2', 2064),   ('ERBB3', 2065),   ('FAT4', 79633),
    ('KMT2D', 8085),   ('NF1', 4763),     ('POLE', 5426),    ('SMAD3', 4088),
    ('FAT1', 2195),    ('NOTCH1', 4851),  ('CREBBP', 1387),  ('KMT2C', 58508),
    ('MSH6', 2956),    ('CDH1', 999),     ('CDKN2A', 1029),  ('MAP2K1', 5604),
    ('FGFR2', 2263),   ('TSC2', 7249),    ('IDH1', 3417),    ('JAK1', 3716),
    ('ATRX', 546),     ('GNAS', 2778),    ('MLH1', 4292),    ('MSH2', 4436),
    ('PMS2', 5395),
]

gene_names_all = [g[0] for g in GENES]
gene_ids = [g[1] for g in GENES]

# Tissue O₂ classification (from paper §3.24, Table: O₂ tier assignment)
TISSUE_O2 = {
    'luad': 'HIGH', 'lusc': 'HIGH', 'nsclc': 'HIGH',
    'brca': 'HIGH', 'breast': 'HIGH',
    'skcm': 'HIGH', 'mel': 'HIGH',
    'ccrcc': 'HIGH', 'prcc': 'HIGH',
    'thca': 'HIGH',
    'coadread': 'HIGH', 'coad': 'HIGH', 'bowel': 'HIGH',
    'stad': 'MEDIUM', 'stomach': 'MEDIUM', 'egc': 'MEDIUM',
    'esca': 'MEDIUM',
    'blca': 'MEDIUM', 'bladder': 'MEDIUM',
    'ucec': 'MEDIUM',
    'cesc': 'MEDIUM',
    'hnsc': 'MEDIUM',
    'chol': 'MEDIUM', 'ihch': 'MEDIUM',
    'hcc': 'LOW',
    'paad': 'LOW', 'pancreas': 'LOW',
    'difg': 'LOW',
    'mbn': 'LOW',
    'soft_tissue': 'LOW',
    'prad': 'LOW', 'prostate': 'LOW',
    'gist': 'LOW',
    'hgsoc': 'LOW',
    'apad': 'LOW',
}

# Wall Cox coefficients from paper §3.23 (Table: Domain Wall Cox Model)
WALL_COEFS = {
    'TP53_coupled': 0.275639,
    'GrowSup_only': 0.040756,
    'Death_only': -0.137876,
    'Aerobic_coupled': -0.042879,
    'Prolif_only': 0.250482,
    'Invade_only': -0.023322,
    'Hypoxic_coupled': -0.905121,
    'Immort_only': -0.135131,
    'Metab_only': -0.47331,
    'Genome': -0.03712,
}

# Wall coupling pairs: (hallmark_a, hallmark_b, coupled_name, only_a_name, only_b_name)
WALL_PAIRS = [
    (1, 2, 'TP53_coupled', 'GrowSup_only', 'Death_only'),
    (0, 4, 'Aerobic_coupled', 'Prolif_only', 'Invade_only'),
    (3, 7, 'Hypoxic_coupled', 'Immort_only', 'Metab_only'),
]

# Hematologic cancer types to exclude (different hallmark biology)
HEME_TYPES = {'aml', 'all', 'cll', 'dlbc', 'mbl', 'mds', 'nhl', 'laml', 'heme',
              'lymph', 'leukemia', 'myeloid', 'lymphoma', 'myeloma'}

BASE = 'https://www.cbioportal.org/api'


# ═══════════════════════════════════════════════════════════════════
# Standard Biostatistics Helpers (no patent content)
# ═══════════════════════════════════════════════════════════════════

def fetch_api(url, data=None, retries=3):
    """Fetch JSON from cBioPortal API."""
    from urllib.request import Request, urlopen
    for attempt in range(retries):
        try:
            body = json.dumps(data).encode('utf-8') if data else None
            method = 'POST' if body else 'GET'
            req = Request(url, data=body, method=method)
            req.add_header('Accept', 'application/json')
            if body:
                req.add_header('Content-Type', 'application/json')
            with urlopen(req, timeout=180) as resp:
                return json.loads(resp.read().decode())
        except Exception as e:
            if attempt == retries - 1:
                raise
            time.sleep(3 * (attempt + 1))


def count_complete_pairs(h):
    """Count how many of the 4 hallmark pairs are fully complete (both active)."""
    return sum(1 for a, b in PAIRS if h[a] and h[b])


def count_domain_walls(h):
    """Count broken pairs (0–4). A broken pair = exactly one hallmark of a pair is active."""
    return sum(1 for a, b in PAIRS if bool(h[a]) != bool(h[b]))


def compute_wall_features(h):
    """Compute the 10 domain wall features from an 8-bit hallmark vector."""
    walls = {'Genome': int(h[6])}
    for h_a, h_b, coupled, only_a, only_b in WALL_PAIRS:
        if h[h_a] and h[h_b]:
            walls[coupled] = 1; walls[only_a] = 0; walls[only_b] = 0
        elif h[h_a] and not h[h_b]:
            walls[coupled] = 0; walls[only_a] = 1; walls[only_b] = 0
        elif not h[h_a] and h[h_b]:
            walls[coupled] = 0; walls[only_a] = 0; walls[only_b] = 1
        else:
            walls[coupled] = 0; walls[only_a] = 0; walls[only_b] = 0
    return walls


def wall_risk_score(h):
    """Compute the domain wall Cox risk score: sum(beta_i * wall_i).
    This is the linear predictor from the Cox PH model (standard biostatistics)."""
    walls = compute_wall_features(h)
    return sum(WALL_COEFS[k] * v for k, v in walls.items())


def mann_whitney_z(x, y):
    """Two-sample Mann-Whitney U test, returns z-score and p-value."""
    n1, n2 = len(x), len(y)
    if n1 < 3 or n2 < 3:
        return 0.0, 1.0
    combined = np.concatenate([x, y])
    ranks = np.argsort(np.argsort(combined)).astype(float) + 1
    U1 = ranks[:n1].sum() - n1 * (n1 + 1) / 2
    mu = n1 * n2 / 2
    sigma = sqrt(n1 * n2 * (n1 + n2 + 1) / 12)
    z = (U1 - mu) / sigma if sigma > 0 else 0.0
    p = erfc(abs(z) / sqrt(2))
    return z, p


def cox_fit_lifelines(X, time, event, feature_names, penalizer=0.01):
    """Fit a Cox PH model using lifelines CoxPHFitter (Efron ties, Ridge penalty).

    Returns:
        params: dict  {feature_name: coefficient}
        se:     dict  {feature_name: standard_error}
        c_index: float
        converged: bool (always True if lifelines doesn't raise)
    """
    import pandas as pd
    from lifelines import CoxPHFitter

    df = pd.DataFrame(X, columns=feature_names)
    df['T'] = time
    df['E'] = event

    cph = CoxPHFitter(penalizer=penalizer)
    cph.fit(df, duration_col='T', event_col='E')

    params = {f: cph.params_[f] for f in feature_names}
    se = {f: cph.summary.loc[f, 'se(coef)'] for f in feature_names}
    return params, se, cph.concordance_index_, True


def classify_o2(cancer_type):
    """Classify a cancer type's tissue O₂ environment."""
    ct = cancer_type.lower().replace('-', '').replace('_', '')
    for key, tier in TISSUE_O2.items():
        if key in ct:
            return tier
    return 'MEDIUM'  # default for unknown types


def hamming_neighbors(state_str):
    """Return all 8 Hamming-distance-1 neighbors of an 8-bit state string."""
    neighbors = []
    for i in range(8):
        arr = list(state_str)
        arr[i] = '0' if arr[i] == '1' else '1'
        neighbors.append(''.join(arr))
    return neighbors


# ═══════════════════════════════════════════════════════════════════
# Data Loading
# ═══════════════════════════════════════════════════════════════════

def load_from_compact(path):
    """Load patient data from the compact JSON (no patent content in this file)."""
    with open(path, 'r', encoding='utf-8') as f:
        raw = json.load(f)
    patients = []
    for p in raw:
        h = p['h'] if isinstance(p['h'], list) else [int(c) for c in p.get('sig', '00000000')]
        patients.append({
            'sig': p.get('sig', ''.join(str(x) for x in h)),
            'hallmarks': h,
            'n_h': sum(h),
            'pairs': count_complete_pairs(h),
            'n_walls': count_domain_walls(h),
            'walls': compute_wall_features(h),
            'wall_score': wall_risk_score(h),
            'os_mo': p.get('os_mo'),
            'deceased': p.get('deceased', 0),
            'has_surv': p.get('os_mo') is not None,
            'study': p.get('study', ''),
            'ctype': p.get('ctype', ''),
            'o2': classify_o2(p.get('ctype', '')),
        })
    return patients


def fetch_fresh():
    """Fetch everything from cBioPortal. Same pipeline as compass_100k.py
    but WITHOUT any eigenvalue / commutator / sigma_z computation."""
    print('  Discovering studies from cBioPortal...')
    all_studies = fetch_api(f'{BASE}/studies?projection=DETAILED&pageSize=10000000')
    print(f'    Total studies on cBioPortal: {len(all_studies)}')

    usable = []
    for study in all_studies:
        sid = study['studyId']
        if 'cellline' in sid or 'ccle' in sid:
            continue
        ct = study.get('cancerTypeId', '').lower()
        nm = study.get('name', '').lower()
        if any(h in ct or h in nm or h in sid for h in HEME_TYPES):
            continue
        try:
            profiles = fetch_api(f'{BASE}/studies/{sid}/molecular-profiles')
            mut_profs = [p for p in profiles if p.get('molecularAlterationType') == 'MUTATION_EXTENDED']
            if not mut_profs:
                continue
            samples = fetch_api(f'{BASE}/studies/{sid}/samples?projection=ID&pageSize=100000')
            if len(samples) < 50:
                continue
            usable.append({
                'study_id': sid,
                'name': study.get('name', sid),
                'n_samples': len(samples),
                'mut_profile': mut_profs[0]['molecularProfileId'],
                'cancer_type': study.get('cancerTypeId', 'unknown'),
            })
        except Exception:
            continue

    usable.sort(key=lambda s: -s['n_samples'])
    print(f'    Usable studies: {len(usable)} ({sum(s["n_samples"] for s in usable):,} potential samples)')

    patients = []
    seen = set()

    for si, info in enumerate(usable):
        sid = info['study_id']
        mut_prof = info['mut_profile']
        label = info['name'][:40]
        print(f'  [{si+1:3d}/{len(usable)}] {label:<42s}', end='', flush=True)

        try:
            samples = fetch_api(f'{BASE}/studies/{sid}/samples?pageSize=100000')
            sample_ids = [s['sampleId'] for s in samples]
            s2p = {s['sampleId']: s['patientId'] for s in samples}

            try:
                mutations = fetch_api(
                    f'{BASE}/molecular-profiles/{mut_prof}/mutations/fetch',
                    data={'sampleListId': f'{sid}_all', 'entrezGeneIds': gene_ids})
            except Exception:
                mutations = []
                for ci in range(0, len(sample_ids), 5000):
                    try:
                        chunk = fetch_api(
                            f'{BASE}/molecular-profiles/{mut_prof}/mutations/fetch',
                            data={'sampleIds': sample_ids[ci:ci+5000], 'entrezGeneIds': gene_ids})
                        mutations.extend(chunk)
                    except Exception:
                        pass

            if not mutations:
                print('  no mutations')
                continue

            s_idx = {s: i for i, s in enumerate(sample_ids)}
            g_idx = {g: i for i, g in enumerate(gene_ids)}
            M_gene = np.zeros((len(sample_ids), len(gene_ids)), dtype=bool)
            for mut in mutations:
                si2 = s_idx.get(mut.get('sampleId', ''))
                gi = g_idx.get(mut.get('entrezGeneId', 0))
                if si2 is not None and gi is not None:
                    M_gene[si2, gi] = True

            M_hm = np.zeros((len(sample_ids), n_h), dtype=bool)
            for i, gn in enumerate(gene_names_all):
                for hm in GENE_TO_HALLMARK.get(gn, []):
                    M_hm[:, hm] |= M_gene[:, i]

            # Survival
            os_status, os_months = {}, {}
            try:
                for c in fetch_api(f'{BASE}/studies/{sid}/clinical-data?clinicalDataType=PATIENT&attributeId=OS_STATUS'):
                    os_status[c['patientId']] = c['value']
                for c in fetch_api(f'{BASE}/studies/{sid}/clinical-data?clinicalDataType=PATIENT&attributeId=OS_MONTHS'):
                    try:
                        os_months[c['patientId']] = float(c['value'])
                    except (ValueError, KeyError):
                        pass
            except Exception:
                pass

            n_added = 0
            for p in range(len(sample_ids)):
                h = M_hm[p]
                if not h.any():
                    continue
                pid = s2p.get(sample_ids[p])
                key = f'{pid}_{sid}'
                if key in seen:
                    continue
                seen.add(key)

                h_list = h.tolist()
                os_mo = os_months.get(pid)
                os_st = os_status.get(pid, '')
                deceased = 1 if os_st in ('1:DECEASED', 'DECEASED') else 0

                patients.append({
                    'sig': ''.join(str(int(x)) for x in h),
                    'hallmarks': [int(x) for x in h_list],
                    'n_h': int(h.sum()),
                    'pairs': count_complete_pairs(h),
                    'n_walls': count_domain_walls(h),
                    'walls': compute_wall_features(h),
                    'wall_score': wall_risk_score(h),
                    'os_mo': os_mo,
                    'deceased': deceased,
                    'has_surv': os_mo is not None,
                    'study': sid,
                    'ctype': info['cancer_type'],
                    'o2': classify_o2(info['cancer_type']),
                })
                n_added += 1

            n_surv = sum(1 for pa in patients[-n_added:] if pa['has_surv']) if n_added else 0
            print(f'  {n_added:5d} pts, {n_surv:4d} surv')
        except Exception as e:
            print(f'  ERROR: {str(e)[:60]}')

        if (si + 1) % 20 == 0:
            print(f'  --- Running total: {len(patients):,} patients ---')
        sys.stdout.flush()

    return patients


# ═══════════════════════════════════════════════════════════════════
# Analysis — reproduces paper claims using standard biostatistics
# ═══════════════════════════════════════════════════════════════════

def run_analysis(patients):
    N = len(patients)
    print()
    print(BAR)
    print(f'  PATIENT COMPASS — REPRODUCIBILITY ANALYSIS (N = {N:,})')
    print(BAR)
    print()

    # ─── A: Dataset summary ───────────────────────────────────────
    n_surv = sum(1 for p in patients if p['has_surv'])
    n_deaths = sum(1 for p in patients if p['deceased'])
    sig_counter = Counter(p['sig'] for p in patients)

    print(f'  DATASET:')
    print(f'    Patients:      {N:>10,}')
    print(f'    With survival: {n_surv:>10,}')
    print(f'    Deaths:        {n_deaths:>10,}')
    print(f'    States:        {len(sig_counter):>10} / 256')
    print()

    # ─── B: Lopsidedness (§3.1) ───────────────────────────────────
    pair_counts = Counter(p['pairs'] for p in patients)
    print(f'  PAIR COMPLETENESS (§3.1):')
    for k in range(5):
        c = pair_counts.get(k, 0)
        pct = c / N * 100
        print(f'    {k} complete pairs: {c:>8,} ({pct:5.1f}%)')
    pct_zero = pair_counts.get(0, 0) / N * 100
    print(f'    >> {pct_zero:.1f}% have zero complete pairs (paper claims 85.8%)')
    print()

    # ─── C: Boltzmann fit (§3.4) ──────────────────────────────────
    ks = np.array([0, 1, 2, 3, 4], dtype=float)
    ns = np.array([pair_counts.get(k, 0) for k in range(5)], dtype=float)
    probs = ns / ns.sum()
    mask = probs > 0
    log_p = np.log(probs[mask])
    coeffs = np.polyfit(ks[mask], log_p, 1)
    beta = -coeffs[0]
    predicted = coeffs[1] + coeffs[0] * ks[mask]
    ss_res = np.sum((log_p - predicted)**2)
    ss_tot = np.sum((log_p - log_p.mean())**2)
    r2 = 1 - ss_res / ss_tot if ss_tot > 0 else 0

    print(f'  BOLTZMANN FIT (§3.4):')
    print(f'    P(k) ∝ exp(-β·k)')
    print(f'    β = {beta:.4f} (paper claims 1.6283)')
    print(f'    R² = {r2:.6f} (paper claims 0.9935)')
    print()

    # Transition ratios (cooperative effect)
    print(f'  COOPERATIVE EFFECT (§3.10):')
    for k in range(4):
        if ns[k] > 0 and ns[k+1] > 0:
            ratio = ns[k+1] / ns[k]
            print(f'    N({k+1})/N({k}) = {ratio:.4f}')
    print(f'    >> Ratios should INCREASE if pair completion is cooperative')
    print()

    # ─── D: Forbidden states (§3.2) ──────────────────────────────
    observed = set(sig_counter.keys())
    all_states = set(format(i, '08b') for i in range(256))
    forbidden = all_states - observed

    print(f'  STATE SPACE (§3.2):')
    print(f'    Observed:  {len(observed)}')
    print(f'    Forbidden: {len(forbidden)} (paper claims 94)')
    top_10 = sig_counter.most_common(10)
    top_10_pct = sum(c for _, c in top_10) / N * 100
    print(f'    Top 10 states cover: {top_10_pct:.1f}% (paper claims 70.0%)')
    print()

    # ─── E: Domain wall survival (§3.21) ──────────────────────────
    surv = [p for p in patients if p['has_surv'] and p['os_mo'] is not None and p['deceased']]

    if len(surv) > 100:
        print(f'  DOMAIN WALL SURVIVAL (§3.21):')
        wall_groups = {}
        for p in surv:
            w = p['n_walls']
            wall_groups.setdefault(w, []).append(p['os_mo'])

        for w in sorted(wall_groups.keys()):
            mos = wall_groups[w]
            print(f'    {w} broken pairs: N={len(mos):>6,}  median OS = {np.median(mos):6.1f} mo  mean OS = {np.mean(mos):6.1f} mo')

        # 0 walls vs 3+ walls
        lo_wall = np.array([p['os_mo'] for p in surv if p['n_walls'] <= 1])
        hi_wall = np.array([p['os_mo'] for p in surv if p['n_walls'] >= 3])
        if len(lo_wall) > 10 and len(hi_wall) > 10:
            z_w, p_w = mann_whitney_z(lo_wall, hi_wall)
            print(f'    LOW walls (0-1) vs HIGH walls (3+):')
            print(f'      z = {z_w:+.4f}, p = {p_w:.2e}')
            print(f'      >> Paper claims z = -19.34, p = 2.7e-83')
        print()

    # ─── F: Wall risk score survival ──────────────────────────────
    if len(surv) > 100:
        scores = np.array([p['wall_score'] for p in surv])
        months = np.array([p['os_mo'] for p in surv])
        med_score = np.median(scores)
        hi = scores >= med_score
        lo = ~hi

        z_ws, p_ws = mann_whitney_z(months[hi], months[lo])
        print(f'  WALL RISK SCORE SURVIVAL:')
        print(f'    High risk (score >= {med_score:.3f}): N={int(hi.sum()):,}, median OS = {np.median(months[hi]):.1f} mo')
        print(f'    Low risk  (score <  {med_score:.3f}): N={int(lo.sum()):,}, median OS = {np.median(months[lo]):.1f} mo')
        print(f'    Mann-Whitney z = {z_ws:+.4f}, p = {p_ws:.2e}')
        print()

    # ─── G: O₂-stratified survival (§3.24-3.26) ──────────────────
    if len(surv) > 100:
        print(f'  O₂-STRATIFIED SURVIVAL (§3.24-3.26):')
        for tier in ['HIGH', 'MEDIUM', 'LOW']:
            tier_pts = [p for p in surv if p['o2'] == tier]
            if len(tier_pts) < 20:
                print(f'    {tier:>6s} O₂: N={len(tier_pts):>5,} (too few)')
                continue
            mos = np.array([p['os_mo'] for p in tier_pts])
            genome_pts = [p for p in tier_pts if p['hallmarks'][6]]
            no_genome = [p for p in tier_pts if not p['hallmarks'][6]]
            if len(genome_pts) > 10 and len(no_genome) > 10:
                z_g, p_g = mann_whitney_z(
                    np.array([p['os_mo'] for p in genome_pts]),
                    np.array([p['os_mo'] for p in no_genome]))
                direction = 'protective' if z_g > 0 else 'harmful'
                print(f'    {tier:>6s} O₂: N={len(tier_pts):>5,}  Genome effect: z={z_g:+.3f} p={p_g:.2e} ({direction})')
            else:
                print(f'    {tier:>6s} O₂: N={len(tier_pts):>5,}  (insufficient Genome+ patients)')
        print(f'    >> Paper claims Genome is harmful in HIGH O₂, protective in LOW O₂')
        print()

    # ─── H: Per-study survival + Stouffer meta-analysis (§3.6) ────
    study_ids = set(p['study'] for p in patients)
    study_z_results = []

    print(f'  PER-STUDY DOMAIN WALL SURVIVAL:')
    print(f'    {"Study":<40s}  {"N":>5s}  {"z":>8s}  {"p":>10s}  {"Δ OS":>8s}')
    print('    ' + '-' * 80)

    for sid in sorted(study_ids):
        s_surv = [p for p in patients if p['study'] == sid and p['has_surv']
                  and p['os_mo'] is not None and p['deceased']]
        if len(s_surv) < 30:
            continue
        lo_wall = np.array([p['os_mo'] for p in s_surv if p['n_walls'] <= 1])
        hi_wall = np.array([p['os_mo'] for p in s_surv if p['n_walls'] >= 2])
        if len(lo_wall) < 5 or len(hi_wall) < 5:
            continue
        z_s, p_s = mann_whitney_z(lo_wall, hi_wall)
        delta = float(np.median(lo_wall) - np.median(hi_wall))
        sig_mark = '**' if p_s < 0.05 else '*' if p_s < 0.10 else ''
        label = sid[:40]
        print(f'    {label:<40s}  {len(s_surv):5d}  {z_s:+8.3f}  {p_s:10.2e}  {delta:+7.1f}mo  {sig_mark}')
        study_z_results.append({'study': sid, 'n': len(s_surv), 'z': z_s, 'p': p_s})

    print()
    if study_z_results:
        zs = np.array([r['z'] for r in study_z_results])
        ns_arr = np.array([r['n'] for r in study_z_results])
        n_tested = len(study_z_results)
        n_sig = sum(1 for r in study_z_results if r['p'] < 0.05)

        # Stouffer unweighted
        z_stouf = zs.sum() / sqrt(n_tested)
        p_stouf = erfc(abs(z_stouf) / sqrt(2))
        # Stouffer weighted
        w = np.sqrt(ns_arr)
        z_wt = (w * zs).sum() / sqrt((w**2).sum())
        p_wt = erfc(abs(z_wt) / sqrt(2))
        # Direction-agnostic (|z|)
        z_abs = np.abs(zs).sum() / sqrt(n_tested)
        p_abs = erfc(abs(z_abs) / sqrt(2))

        print(f'  META-ANALYSIS — Stouffer (§3.6):')
        print(f'    Studies tested:  {n_tested}')
        print(f'    Significant p<0.05: {n_sig} ({n_sig/n_tested*100:.0f}%)')
        print(f'    Unweighted:   z = {z_stouf:+.3f}, p = {p_stouf:.2e}')
        print(f'    Weighted:     z = {z_wt:+.3f}, p = {p_wt:.2e}')
        print(f'    |z| (direction-agnostic): z = {z_abs:+.3f}, p = {p_abs:.2e}')
        print(f'    >> Paper claims Z_|z| = +15.29, p = 8.9e-53')
        print()

    # ─── I: Pair-specific survival (§3.9) ─────────────────────────
    print(f'  PAIR-SPECIFIC SURVIVAL (§3.9):')
    for pair_idx, (h_a, h_b) in enumerate(PAIRS):
        name = f'{SHORT[h_a]}+{SHORT[h_b]}'
        comp = [p for p in surv if p['hallmarks'][h_a] and p['hallmarks'][h_b]]
        inc = [p for p in surv if not (p['hallmarks'][h_a] and p['hallmarks'][h_b])]
        if len(comp) > 30 and len(inc) > 30:
            z_p, p_p = mann_whitney_z(
                np.array([p['os_mo'] for p in comp]),
                np.array([p['os_mo'] for p in inc]))
            delta = float(np.median([p['os_mo'] for p in comp]) - np.median([p['os_mo'] for p in inc]))
            print(f'    Pair {pair_idx+1} ({name:15s}): N_comp={len(comp):>6,} N_inc={len(inc):>6,}  z={z_p:+.3f} p={p_p:.2e} Δ={delta:+.1f}mo')
    print()

    # ─── J: Frustrated Proliferator (§3.23) ───────────────────────
    if len(surv) > 100:
        frust = [p for p in surv if p['hallmarks'][0] and not p['hallmarks'][4]]  # Prolif_only
        non_frust = [p for p in surv if not (p['hallmarks'][0] and not p['hallmarks'][4])]
        if len(frust) > 20 and len(non_frust) > 20:
            z_f, p_f = mann_whitney_z(
                np.array([p['os_mo'] for p in frust]),
                np.array([p['os_mo'] for p in non_frust]))
            hr = exp(WALL_COEFS['Prolif_only'])
            print(f'  FRUSTRATED PROLIFERATOR (§3.23):')
            print(f'    Prolif only: N={len(frust):,}, median OS={np.median([p["os_mo"] for p in frust]):.1f}mo')
            print(f'    Others:      N={len(non_frust):,}, median OS={np.median([p["os_mo"] for p in non_frust]):.1f}mo')
            print(f'    z = {z_f:+.4f}, p = {p_f:.2e}')
            print(f'    Cox HR = {hr:.2f} (paper claims HR=1.81 in LOW O₂)')
            print()

    # ─── K: Forbidden state topology ──────────────────────────────
    print(f'  FORBIDDEN STATE TOPOLOGY (§3.2, §3.5):')
    for cp in range(5):
        poss = [s for s in all_states if count_complete_pairs([int(c) for c in s]) == cp]
        obs = [s for s in poss if s in observed]
        forb = [s for s in poss if s not in observed]
        pct = len(forb) / len(poss) * 100 if poss else 0
        print(f'    {cp} pairs: {len(obs):>3} observed, {len(forb):>3} forbidden ({pct:.0f}% forbidden)')
    print()

    # ─── L: Cox PH model — re-derive wall coefficients from scratch ─
    # Model: 10 wall features + 2 O₂ indicators = 12 covariates
    # lifelines CoxPHFitter(penalizer=0.01), Efron ties, O₂-tier patients only
    cox_surv = [p for p in patients if p['has_surv'] and p['os_mo'] is not None
                and p['os_mo'] > 0 and p['deceased'] is not None
                and TISSUE_O2.get(p.get('ctype', '')) is not None]
    if len(cox_surv) > 500:
        print(f'  COX PH MODEL — RE-DERIVING WALL COEFFICIENTS (§3.23):')
        print(f'    Fitting Cox PH (lifelines, Efron ties, penalizer=0.01) on {len(cox_surv):,} patients...')
        print(f'    (12 covariates: 10 walls + O₂_high + O₂_low)')

        # 10 wall features + O2_high + O2_low
        wall_names = list(WALL_COEFS.keys())
        feature_names = wall_names + ['O2_high', 'O2_low']
        X_cox = np.array([
            [p['walls'].get(f, 0) for f in wall_names]
            + [1 if TISSUE_O2[p['ctype']] == 'HIGH' else 0,
               1 if TISSUE_O2[p['ctype']] == 'LOW' else 0]
            for p in cox_surv
        ], dtype=float)
        t_cox = np.array([p['os_mo'] for p in cox_surv], dtype=float)
        e_cox = np.array([p['deceased'] for p in cox_surv], dtype=float)

        params, se_dict, c_index, converged = cox_fit_lifelines(
            X_cox, t_cox, e_cox, feature_names)

        status = 'CONVERGED' if converged else 'DID NOT CONVERGE'
        print(f'    Status: {status}, C-index: {c_index:.4f}')
        print(f'    {"Feature":<20s}  {"Paper β":>10s}  {"Fitted β":>10s}  {"SE":>8s}  {"HR":>6s}  {"Match?":>8s}')
        print('    ' + '-' * 70)

        all_close = True
        for feat in wall_names:
            paper_b = WALL_COEFS[feat]
            fit_b = params[feat]
            se = se_dict[feat]
            hr = exp(fit_b)
            close = abs(fit_b - paper_b) < max(2 * se, 0.01)
            mark = '✓' if close else '✗'
            if not close:
                all_close = False
            print(f'    {feat:<20s}  {paper_b:+10.6f}  {fit_b:+10.6f}  {se:8.4f}  {hr:6.3f}  {mark:>8s}')

        print()
        if all_close:
            print(f'    >> All coefficients independently re-derived within tolerance.')
        else:
            print(f'    >> Some coefficients differ — see SE column for confidence intervals.')
            print(f'    >> (Differences may reflect penalization or subsample effects.)')
        print()

    # ─── Summary ──────────────────────────────────────────────────
    print(BAR)
    print('  REPRODUCIBILITY SUMMARY')
    print(BAR)
    print()
    checks = [
        ('Patients ≥ 100,000', N >= 100000),
        ('States ≈ 162', 155 <= len(observed) <= 170),
        ('Forbidden ≈ 94', 86 <= len(forbidden) <= 101),
        ('Lopsidedness > 80%', pct_zero > 80),
        ('β ≈ 1.63', abs(beta - 1.63) < 0.15),
        ('R² > 0.99', r2 > 0.99),
        ('Top 10 > 60%', top_10_pct > 60),
    ]
    for label, ok in checks:
        status = '✓ PASS' if ok else '✗ FAIL'
        print(f'    {status}  {label}')
    print()


# ═══════════════════════════════════════════════════════════════════
# Main
# ═══════════════════════════════════════════════════════════════════

if __name__ == '__main__':
    t0 = time.time()
    print(BAR)
    print('  PATIENT COMPASS — REPRODUCIBILITY SCRIPT')
    print('  Methods: domain walls, Cox PH, Mann-Whitney, Stouffer meta-analysis')
    print('  NO eigenvalue computation. NO spectral methods. Standard biostatistics only.')
    print(BAR)
    print()

    if '--fetch' in sys.argv:
        patients = fetch_fresh()
    elif '--compact' in sys.argv:
        idx = sys.argv.index('--compact') + 1
        path = sys.argv[idx]
        print(f'  Loading compact patient data from {path}')
        patients = load_from_compact(path)
    else:
        # Try compact file first, then results JSON
        script_dir = os.path.dirname(os.path.abspath(__file__))
        compact_path = os.path.join(script_dir, 'compass_patients_compact.json')
        if os.path.exists(compact_path):
            print(f'  Loading cached data from {compact_path}')
            patients = load_from_compact(compact_path)
        else:
            print('  No cached data found. Use --fetch to download from cBioPortal,')
            print('  or --compact <path> to load a compact patient JSON file.')
            sys.exit(1)

    print(f'  Loaded {len(patients):,} patients in {time.time()-t0:.1f}s')
    run_analysis(patients)

    print(f'  Total time: {time.time()-t0:.1f}s')
    print(BAR)
